### ISSUE TITLE
Travis CI is not working (ImportError: No module named 'typing')

### ISSUE THREAD

**Issue by Milly** [tyru/open-browser.vim#125]
Currentry Travis CI is not working.

[Logs](https://travis-ci.org/tyru/open-browser.vim/jobs/604890927)
```
$ vint $VIM_FILES
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.8/bin/vint", line 7, in <module>
    from vint import main
  File "/home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/vint/__init__.py", line 1, in <module>
    from vint.bootstrap import (
  File "/home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/vint/bootstrap.py", line 5, in <module>
    from vint.linting.cli import CLI
  File "/home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/vint/linting/cli.py", line 7, in <module>
    from vint.linting.linter import Linter
  File "/home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/vint/linting/linter.py", line 5, in <module>
    from vint.encodings.decoder import EncodingDetectionError
  File "/home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/vint/encodings/decoder.py", line 2, in <module>
    from typing import Dict, Any
ImportError: No module named 'typing'
The command "vint $VIM_FILES" exited with 1.
```

**Comment by tyru** [comment]
Thanks, this problem was fixed
